/*
 * Flowable REST API
 *
 * # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bpmn
import (
	"time"
)

type TaskQueryRequest struct {
	Start int32 `json:"start,omitempty"`
	Size int32 `json:"size,omitempty"`
	Sort string `json:"sort,omitempty"`
	Order string `json:"order,omitempty"`
	Name string `json:"name,omitempty"`
	NameLike string `json:"nameLike,omitempty"`
	Description string `json:"description,omitempty"`
	DescriptionLike string `json:"descriptionLike,omitempty"`
	Priority int32 `json:"priority,omitempty"`
	MinimumPriority int32 `json:"minimumPriority,omitempty"`
	MaximumPriority int32 `json:"maximumPriority,omitempty"`
	Assignee string `json:"assignee,omitempty"`
	AssigneeLike string `json:"assigneeLike,omitempty"`
	Owner string `json:"owner,omitempty"`
	OwnerLike string `json:"ownerLike,omitempty"`
	Unassigned bool `json:"unassigned,omitempty"`
	DelegationState string `json:"delegationState,omitempty"`
	CandidateUser string `json:"candidateUser,omitempty"`
	CandidateGroup string `json:"candidateGroup,omitempty"`
	CandidateGroupIn []string `json:"candidateGroupIn,omitempty"`
	IgnoreAssignee bool `json:"ignoreAssignee,omitempty"`
	InvolvedUser string `json:"involvedUser,omitempty"`
	ProcessInstanceId string `json:"processInstanceId,omitempty"`
	ProcessInstanceIdWithChildren string `json:"processInstanceIdWithChildren,omitempty"`
	WithoutProcessInstanceId bool `json:"withoutProcessInstanceId,omitempty"`
	ProcessInstanceBusinessKey string `json:"processInstanceBusinessKey,omitempty"`
	ProcessInstanceBusinessKeyLike string `json:"processInstanceBusinessKeyLike,omitempty"`
	ProcessDefinitionId string `json:"processDefinitionId,omitempty"`
	ProcessDefinitionKey string `json:"processDefinitionKey,omitempty"`
	ProcessDefinitionName string `json:"processDefinitionName,omitempty"`
	ProcessDefinitionKeyLike string `json:"processDefinitionKeyLike,omitempty"`
	ProcessDefinitionNameLike string `json:"processDefinitionNameLike,omitempty"`
	ExecutionId string `json:"executionId,omitempty"`
	CreatedOn time.Time `json:"createdOn,omitempty"`
	CreatedBefore time.Time `json:"createdBefore,omitempty"`
	CreatedAfter time.Time `json:"createdAfter,omitempty"`
	ExcludeSubTasks bool `json:"excludeSubTasks,omitempty"`
	TaskDefinitionKey string `json:"taskDefinitionKey,omitempty"`
	TaskDefinitionKeyLike string `json:"taskDefinitionKeyLike,omitempty"`
	TaskDefinitionKeys []string `json:"taskDefinitionKeys,omitempty"`
	DueDate time.Time `json:"dueDate,omitempty"`
	DueBefore time.Time `json:"dueBefore,omitempty"`
	DueAfter time.Time `json:"dueAfter,omitempty"`
	WithoutDueDate bool `json:"withoutDueDate,omitempty"`
	Active bool `json:"active,omitempty"`
	IncludeTaskLocalVariables bool `json:"includeTaskLocalVariables,omitempty"`
	IncludeProcessVariables bool `json:"includeProcessVariables,omitempty"`
	ScopeDefinitionId string `json:"scopeDefinitionId,omitempty"`
	ScopeId string `json:"scopeId,omitempty"`
	WithoutScopeId bool `json:"withoutScopeId,omitempty"`
	ScopeType string `json:"scopeType,omitempty"`
	PropagatedStageInstanceId string `json:"propagatedStageInstanceId,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	TenantIdLike string `json:"tenantIdLike,omitempty"`
	WithoutTenantId bool `json:"withoutTenantId,omitempty"`
	CandidateOrAssigned string `json:"candidateOrAssigned,omitempty"`
	Category string `json:"category,omitempty"`
	CategoryIn []string `json:"categoryIn,omitempty"`
	CategoryNotIn []string `json:"categoryNotIn,omitempty"`
	WithoutCategory bool `json:"withoutCategory,omitempty"`
	TaskVariables []QueryVariable `json:"taskVariables,omitempty"`
	ProcessInstanceVariables []QueryVariable `json:"processInstanceVariables,omitempty"`
}
