/*
 * Flowable REST API
 *
 * # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bpmn

type Process struct {
	Id string `json:"id,omitempty"`
	XmlRowNumber int32 `json:"xmlRowNumber,omitempty"`
	XmlColumnNumber int32 `json:"xmlColumnNumber,omitempty"`
	ExtensionElements map[string][]ExtensionElement `json:"extensionElements,omitempty"`
	Attributes map[string][]ExtensionAttribute `json:"attributes,omitempty"`
	Name string `json:"name,omitempty"`
	Executable bool `json:"executable,omitempty"`
	Documentation string `json:"documentation,omitempty"`
	IoSpecification *IoSpecification `json:"ioSpecification,omitempty"`
	ExecutionListeners []FlowableListener `json:"executionListeners,omitempty"`
	Lanes []Lane `json:"lanes,omitempty"`
	DataObjects []ValuedDataObject `json:"dataObjects,omitempty"`
	CandidateStarterUsers []string `json:"candidateStarterUsers,omitempty"`
	CandidateStarterGroups []string `json:"candidateStarterGroups,omitempty"`
	EventListeners []EventListener `json:"eventListeners,omitempty"`
	FlowElementMap map[string]FlowElement `json:"flowElementMap,omitempty"`
	ArtifactMap map[string]Artifact `json:"artifactMap,omitempty"`
	InitialFlowElement *FlowElement `json:"initialFlowElement,omitempty"`
	EnableEagerExecutionTreeFetching bool `json:"enableEagerExecutionTreeFetching,omitempty"`
	FlowElements []FlowElement `json:"flowElements,omitempty"`
	Artifacts []Artifact `json:"artifacts,omitempty"`
}
