/*
 * Flowable REST API
 *
 * # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bpmn

type ExecutionResponse struct {
	Id string `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	ParentId string `json:"parentId,omitempty"`
	ParentUrl string `json:"parentUrl,omitempty"`
	SuperExecutionId string `json:"superExecutionId,omitempty"`
	SuperExecutionUrl string `json:"superExecutionUrl,omitempty"`
	ProcessInstanceId string `json:"processInstanceId,omitempty"`
	ProcessInstanceUrl string `json:"processInstanceUrl,omitempty"`
	Suspended bool `json:"suspended,omitempty"`
	ActivityId string `json:"activityId,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
}
