/*
 * Flowable REST API
 *
 * # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bpmn

type HistoricDetailQueryRequest struct {
	Start int32 `json:"start,omitempty"`
	Size int32 `json:"size,omitempty"`
	Sort string `json:"sort,omitempty"`
	Order string `json:"order,omitempty"`
	Id string `json:"id,omitempty"`
	ProcessInstanceId string `json:"processInstanceId,omitempty"`
	ExecutionId string `json:"executionId,omitempty"`
	ActivityInstanceId string `json:"activityInstanceId,omitempty"`
	TaskId string `json:"taskId,omitempty"`
	SelectOnlyFormProperties bool `json:"selectOnlyFormProperties,omitempty"`
	SelectOnlyVariableUpdates bool `json:"selectOnlyVariableUpdates,omitempty"`
}
