/*
 * Flowable REST API
 *
 * # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bpmn

type ActivityInstanceQueryRequest struct {
	Start int32 `json:"start,omitempty"`
	Size int32 `json:"size,omitempty"`
	Sort string `json:"sort,omitempty"`
	Order string `json:"order,omitempty"`
	ActivityId string `json:"activityId,omitempty"`
	ActivityInstanceId string `json:"activityInstanceId,omitempty"`
	ActivityName string `json:"activityName,omitempty"`
	ActivityType string `json:"activityType,omitempty"`
	ExecutionId string `json:"executionId,omitempty"`
	Finished bool `json:"finished,omitempty"`
	TaskAssignee string `json:"taskAssignee,omitempty"`
	ProcessInstanceId string `json:"processInstanceId,omitempty"`
	ProcessDefinitionId string `json:"processDefinitionId,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	TenantIdLike string `json:"tenantIdLike,omitempty"`
	WithoutTenantId bool `json:"withoutTenantId,omitempty"`
}
