/*
 * Flowable REST API
 *
 * # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bpmn
import (
	"time"
)

type HistoricTaskInstanceResponse struct {
	Id string `json:"id,omitempty"`
	ProcessDefinitionId string `json:"processDefinitionId,omitempty"`
	ProcessDefinitionUrl string `json:"processDefinitionUrl,omitempty"`
	ProcessInstanceId string `json:"processInstanceId,omitempty"`
	ProcessInstanceUrl string `json:"processInstanceUrl,omitempty"`
	ExecutionId string `json:"executionId,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	DeleteReason string `json:"deleteReason,omitempty"`
	Owner string `json:"owner,omitempty"`
	Assignee string `json:"assignee,omitempty"`
	StartTime time.Time `json:"startTime,omitempty"`
	EndTime time.Time `json:"endTime,omitempty"`
	DurationInMillis int64 `json:"durationInMillis,omitempty"`
	WorkTimeInMillis int64 `json:"workTimeInMillis,omitempty"`
	ClaimTime time.Time `json:"claimTime,omitempty"`
	TaskDefinitionKey string `json:"taskDefinitionKey,omitempty"`
	FormKey string `json:"formKey,omitempty"`
	Priority int32 `json:"priority,omitempty"`
	DueDate time.Time `json:"dueDate,omitempty"`
	ParentTaskId string `json:"parentTaskId,omitempty"`
	Url string `json:"url,omitempty"`
	Variables []RestVariable `json:"variables,omitempty"`
	ScopeDefinitionId string `json:"scopeDefinitionId,omitempty"`
	ScopeId string `json:"scopeId,omitempty"`
	SubScopeId string `json:"subScopeId,omitempty"`
	ScopeType string `json:"scopeType,omitempty"`
	PropagatedStageInstanceId string `json:"propagatedStageInstanceId,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	Category string `json:"category,omitempty"`
}
