/*
 * Flowable REST API
 *
 * # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bpmn

type ProcessDefinitionResponse struct {
	Id string `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Key string `json:"key,omitempty"`
	Version int32 `json:"version,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	DeploymentId string `json:"deploymentId,omitempty"`
	DeploymentUrl string `json:"deploymentUrl,omitempty"`
	// Contains the actual deployed BPMN 2.0 xml.
	Resource string `json:"resource,omitempty"`
	// Contains a graphical representation of the process, null when no diagram is available.
	DiagramResource string `json:"diagramResource,omitempty"`
	Category string `json:"category,omitempty"`
	// Indicates the process definition contains graphical information (BPMN DI).
	GraphicalNotationDefined bool `json:"graphicalNotationDefined,omitempty"`
	Suspended bool `json:"suspended,omitempty"`
	StartFormDefined bool `json:"startFormDefined,omitempty"`
}
