/*
 * Flowable REST API
 *
 * # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bpmn
import (
	"time"
)

type BulkTasksRequest struct {
	Owner string `json:"owner,omitempty"`
	Assignee string `json:"assignee,omitempty"`
	DelegationState string `json:"delegationState,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	DueDate time.Time `json:"dueDate,omitempty"`
	Priority int32 `json:"priority,omitempty"`
	ParentTaskId string `json:"parentTaskId,omitempty"`
	Category string `json:"category,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	FormKey string `json:"formKey,omitempty"`
	OwnerSet bool `json:"ownerSet,omitempty"`
	AssigneeSet bool `json:"assigneeSet,omitempty"`
	DelegationStateSet bool `json:"delegationStateSet,omitempty"`
	NameSet bool `json:"nameSet,omitempty"`
	DescriptionSet bool `json:"descriptionSet,omitempty"`
	DuedateSet bool `json:"duedateSet,omitempty"`
	PrioritySet bool `json:"prioritySet,omitempty"`
	ParentTaskIdSet bool `json:"parentTaskIdSet,omitempty"`
	CategorySet bool `json:"categorySet,omitempty"`
	TenantIdSet bool `json:"tenantIdSet,omitempty"`
	FormKeySet bool `json:"formKeySet,omitempty"`
	TaskIds []string `json:"taskIds,omitempty"`
}
