/*
 * Flowable REST API
 *
 * # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bpmn
import (
	"time"
)

type HistoricTaskInstanceQueryRequest struct {
	Start int32 `json:"start,omitempty"`
	Size int32 `json:"size,omitempty"`
	Sort string `json:"sort,omitempty"`
	Order string `json:"order,omitempty"`
	TaskId string `json:"taskId,omitempty"`
	ProcessInstanceId string `json:"processInstanceId,omitempty"`
	ProcessInstanceIdWithChildren string `json:"processInstanceIdWithChildren,omitempty"`
	WithoutProcessInstanceId bool `json:"withoutProcessInstanceId,omitempty"`
	ProcessBusinessKey string `json:"processBusinessKey,omitempty"`
	ProcessBusinessKeyLike string `json:"processBusinessKeyLike,omitempty"`
	ProcessDefinitionId string `json:"processDefinitionId,omitempty"`
	ProcessDefinitionKey string `json:"processDefinitionKey,omitempty"`
	ProcessDefinitionKeyLike string `json:"processDefinitionKeyLike,omitempty"`
	ProcessDefinitionName string `json:"processDefinitionName,omitempty"`
	ProcessDefinitionNameLike string `json:"processDefinitionNameLike,omitempty"`
	ExecutionId string `json:"executionId,omitempty"`
	TaskName string `json:"taskName,omitempty"`
	TaskNameLike string `json:"taskNameLike,omitempty"`
	TaskDescription string `json:"taskDescription,omitempty"`
	TaskDescriptionLike string `json:"taskDescriptionLike,omitempty"`
	TaskDefinitionKey string `json:"taskDefinitionKey,omitempty"`
	TaskDefinitionKeyLike string `json:"taskDefinitionKeyLike,omitempty"`
	TaskDefinitionKeys []string `json:"taskDefinitionKeys,omitempty"`
	TaskCategory string `json:"taskCategory,omitempty"`
	TaskCategoryIn []string `json:"taskCategoryIn,omitempty"`
	TaskCategoryNotIn []string `json:"taskCategoryNotIn,omitempty"`
	TaskWithoutCategory bool `json:"taskWithoutCategory,omitempty"`
	TaskDeleteReason string `json:"taskDeleteReason,omitempty"`
	TaskDeleteReasonLike string `json:"taskDeleteReasonLike,omitempty"`
	TaskAssignee string `json:"taskAssignee,omitempty"`
	TaskAssigneeLike string `json:"taskAssigneeLike,omitempty"`
	TaskOwner string `json:"taskOwner,omitempty"`
	TaskOwnerLike string `json:"taskOwnerLike,omitempty"`
	TaskInvolvedUser string `json:"taskInvolvedUser,omitempty"`
	TaskPriority int32 `json:"taskPriority,omitempty"`
	TaskMinPriority int32 `json:"taskMinPriority,omitempty"`
	TaskMaxPriority int32 `json:"taskMaxPriority,omitempty"`
	Finished bool `json:"finished,omitempty"`
	ProcessFinished bool `json:"processFinished,omitempty"`
	ParentTaskId string `json:"parentTaskId,omitempty"`
	DueDate time.Time `json:"dueDate,omitempty"`
	DueDateAfter time.Time `json:"dueDateAfter,omitempty"`
	DueDateBefore time.Time `json:"dueDateBefore,omitempty"`
	WithoutDueDate bool `json:"withoutDueDate,omitempty"`
	TaskCreatedOn time.Time `json:"taskCreatedOn,omitempty"`
	TaskCreatedBefore time.Time `json:"taskCreatedBefore,omitempty"`
	TaskCreatedAfter time.Time `json:"taskCreatedAfter,omitempty"`
	TaskCompletedOn time.Time `json:"taskCompletedOn,omitempty"`
	TaskCompletedBefore time.Time `json:"taskCompletedBefore,omitempty"`
	TaskCompletedAfter time.Time `json:"taskCompletedAfter,omitempty"`
	IncludeTaskLocalVariables bool `json:"includeTaskLocalVariables,omitempty"`
	IncludeProcessVariables bool `json:"includeProcessVariables,omitempty"`
	TaskVariables []QueryVariable `json:"taskVariables,omitempty"`
	ProcessVariables []QueryVariable `json:"processVariables,omitempty"`
	ScopeDefinitionId string `json:"scopeDefinitionId,omitempty"`
	ScopeId string `json:"scopeId,omitempty"`
	WithoutScopeId bool `json:"withoutScopeId,omitempty"`
	ScopeType string `json:"scopeType,omitempty"`
	PropagatedStageInstanceId string `json:"propagatedStageInstanceId,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	TenantIdLike string `json:"tenantIdLike,omitempty"`
	WithoutTenantId bool `json:"withoutTenantId,omitempty"`
	WithoutDeleteReason bool `json:"withoutDeleteReason,omitempty"`
	TaskCandidateGroup string `json:"taskCandidateGroup,omitempty"`
	IgnoreTaskAssignee bool `json:"ignoreTaskAssignee,omitempty"`
}
