/*
 * Flowable REST API
 *
 * # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bpmn
import (
	"time"
)

type AttachmentResponse struct {
	Id string `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Name string `json:"name,omitempty"`
	UserId string `json:"userId,omitempty"`
	Description string `json:"description,omitempty"`
	// Can be any arbitrary value. When a valid formatted media-type (e.g. application/xml, text/plain) is included, the binary content HTTP response content-type will be set the given value.
	Type_ string `json:"type,omitempty"`
	TaskUrl string `json:"taskUrl,omitempty"`
	ProcessInstanceUrl string `json:"processInstanceUrl,omitempty"`
	// contentUrl:In case the attachment is a link to an external resource, the externalUrl contains the URL to the external content. If the attachment content is present in the Flowable engine, the contentUrl will contain an URL where the binary content can be streamed from.
	ExternalUrl string `json:"externalUrl,omitempty"`
	ContentUrl string `json:"contentUrl,omitempty"`
	Time time.Time `json:"time,omitempty"`
}
